### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by NSMyself** [imjog/Calculator-iOS#3]
Would you consider updating the existing codebase for Swift 4 and Xcode 9? 
I could totally do it if you want to.

**Comment by jogendra** [comment]
@NSMyself  yes please upgrade to swift 4 and keep swift swift3 version in separate folder (give it a name 
_**Calculator-iOS_Swift_3**_ and keep swift 4 version separately and give it name **_Calculator-iOS_Swift_4_**
Thanks :)
